# Built with Jekyll 3.2.0

# Setup
title:               'ds@swat'
tagline:             ''
description:         'ds@swat digital editions for sharing & collaborative annotation of public domain & creatively licensed texts
'
url:                 'http://elotroalex.github.io'
baseurl:             '/digital-editions'

# About/contact
author:
  name:              Nabil Kashyap
  url:               https://twitter.com/_nabilk
  email:             nkashya1@swarthmore.edu

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             0.0.6

# Exclusions from the final site
exclude: [optional, vendor]


